language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - secure: "gN7mPh4iexPARgYyZypCA5ukXIMVhRBevMn3i4vUXgyXs8rnxmOp+PE/NppW0bLOlgHw7OOx8A/MB8mJ/LCRaO5H9rMXBtiQL57+3NZihUUB9d7yLIDSyA9UjzWDgRjB2MdwnsJ34P8V9MiC5VDUgI6eB2zIBMm0oGPuHBiqjvg4YpAzS9SJp+nNADSYT8fZu82HhHOZM9YQ8eW3nQd64b1mFknhXr7Xv12X8JltyNsAuAZXy563lYE7MNw79KYTO7IK1eP4gCS4ti2FGuP5AHxwQs4VMgVprAvPgq+MKyK/BdDRwaj5iCH89OwxMRMrZeEq+D7ZfRYJ6eplZy8N2wdfT+jZJcyj8R4ttCj+rdFYl2TOyiVq5M/kf5uyrJgFEDOEQ/pqsi9s0F97Gt8BDqNYU4nCsZ3frJjLEhzhN5SZjlffv/vylhudy4VHWabRenkrA2RVCpQO9eUMxbhvTEAK3PGDA/G9eQJk745uRFASaKDYOONYiEJQrQJtHjnvvzniJwThAQU1F/XF5eMYpd8CPUCUj5FRcxaBZGc9cFvVACmfNr8mtaMoimFNtNL/Bok2OHqu8NkuCOlNQsQ9+xHmglzVtnLdYPuxxVQfXkDhsB1HhnhKYDpINah19vNaXwqaUdzVpNHrs6kP3RQ+qpJwNQtpzY4d/sYl1jMX7Yk=" # MAVEN_OSSRH_USERNAME
  - secure: "eeg/LG6klFlR0puyxqFk941cxew56jdpWhfvTYMD74Hg+vyaW6A1i+4DTlUmp3rjJIABoVh5P6Ou+0lc7VaNR3XIgI5HuO35+5R2q0cvUX0+t2LelT5W4IEOTLA75qAVG81MF1AVZrLVnNupbZgoNmNkX/pnE0suB/Po7fnQIT2y3M9qG+2svSEvZ/XnpQj8ga4BL2qf+7fnshGcV/w0Z7bbTXg0x7DBge53KpINTytu2eCYvPYMZc3KLEGqoW+8WDE3GxQujphfQwDy6P/gdcEW9jg0AOEH2F/F4buJFCpEsTmNjUGA2KJiDMXvenM1DkASNiOd02HJm+enjd85vbPAsvJRjIepW5wLnWwPV+cebsfTs2hoeggkLEUihkWrS6sLtQGKxLwVX36AuuM/FRRDqeqDbh5BIprm+f49PTbuRms5fpdowkyDVYCw3h6E119KeqPILW8yB9aSyYchDENxzmrW0pH0g7pLn1H8uzvAqYgTdtWcFUKpmkxGnoq7ad6VcxnPqD3d1rYp5M/NZ7h6Z9ANNZLjcQGvq8K43fOHi0Aba3IVIxoukarYAPIyE1BdwUquVR+bR8J6GXk/oXf6DAmUADoJOT/lEFeDJx79QudC3Q1SMqZUigpobyEdRpAUl+VOj5eMtdMODSx6BLeF3GJCNLItfFQx3QvwR9w=" # MAVEN_OSSRH_PASSWORD
  - secure: "iAHuyaR9td8axBotfVepk5FVzQ+s2kDDCjyBi7nps+RgSY23AhYGpAu0lsjB9hlVjgBvBerNdZ/pYBv8EZnDft+vqivhrm14W4MoSfkHBAZyfA5Hae9BejrO/TW/Nq7CTsnqrzSsaD55GxuveXFLmghmrRoG+WlPgCCDGwErxDO6oorAF/RGAA1bonulNKFP7Pl7iMNW3OmhGyrg7anzNvjZsBvL12100IHeqUWCG1p5cJhBP4L7+7MGGUnbqqmQA0+AfXIz9cWj4PoJLVQyNqCyko5SVv+jQUiZJ6x9i92tpLmzVZbQ68ENKosC12GZqkfOoWgy2ynuENWim4bFD/xhb3WOkoa+ZHc+iHOef6B+GGx+DHy+bW9dY2DpEhudQyQjCa2YxHoZJDXxKBA/jRysvPHSREasU+V8qe8cZEsIVRpGZdGPaiOc3Vk7xDTUjDMu1UxTVVhaJzsy5szrRqqGpv53agaVQopN0F8kLy7DndYY5zKaqetErGxhD8AWdC6wezYu+VKmEdx/25NzfWNm+zqfTtUTYuzaFgtIiMgdLLYmuUAkYRqCvLuuj+YKn+RYkwCU4OPG9eyvFoenX3sewcz6buq9aDDuB6cotCErwwYRns3Iyg2DKR4SXJg/zsiimsHEi0c5tv1BZRtay0j2AK3bT3UPwRYQn7ZmW/M=" # MAVEN_GPG_PASSPHRASE
script: mvn -fJNI/pom.xml clean install
before_deploy:
- gpg --import 34C80F11.gpg
deploy:
- provider: script # SNAPSHOTS
  script: mvn -fJNI/pom.xml clean deploy -DskipTests -Prelease --settings JNI/settings.xml
  on:
    repo: cryptomator/native-functions
    branch: develop
    condition: $TRAVIS_TAG = ''
- provider: script # RELEASES
  script: mvn -fJNI/pom.xml clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease --settings JNI/settings.xml
  on:
    repo: cryptomator/native-functions
    tags: true
